-- PostgreSQL / Supabase schema (snake_case)
-- Derived from schema.sql (MySQL)

-- Extensions
create extension if not exists pgcrypto;

-- Enums
do $$ begin
  create type user_role as enum ('ADMIN', 'USER');
exception when duplicate_object then null; end $$;

do $$ begin
  create type event_category as enum ('SENIORS', 'REEAP', 'LAEP', 'JEUNESSE', 'ACCES_DROITS', 'ANIME_QUARTIER', 'GENERAL');
exception when duplicate_object then null; end $$;

do $$ begin
  create type event_status as enum ('DRAFT', 'PUBLISHED', 'CANCELLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type registration_status as enum ('PENDING', 'EMAIL_CONFIRMED', 'CONFIRMED', 'CANCELLED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type team_category as enum ('SENIORS', 'REEAP', 'LAEP', 'JEUNESSE', 'GENERAL');
exception when duplicate_object then null; end $$;

do $$ begin
  create type post_status as enum ('DRAFT', 'PUBLISHED', 'ARCHIVED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type contact_status as enum ('NEW', 'READ', 'REPLIED');
exception when duplicate_object then null; end $$;

do $$ begin
  create type partner_category as enum ('INSTITUTIONAL', 'ASSOCIATIF', 'PRIVE');
exception when duplicate_object then null; end $$;

-- Tables
create table if not exists public.users (
  id            bigint generated by default as identity primary key,
  email         text not null unique,
  password_hash text not null,
  name          text not null,
  role          user_role not null default 'ADMIN',
  active        boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create table if not exists public.events (
  id               bigint generated by default as identity primary key,
  title            text not null,
  description      text not null,
  content          text,
  date             timestamptz not null,
  time             text,
  location         text not null,
  image_url        text,
  category         event_category not null,
  status           event_status not null default 'DRAFT',
  featured         boolean not null default false,
  max_participants integer,
  tags             text,
  created_by_id    bigint references public.users(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.registrations (
  id                   text primary key,
  first_name           text not null,
  last_name            text not null,
  email                text not null,
  phone                text not null,
  message              text,
  status               registration_status not null default 'PENDING',
  event_id             bigint not null references public.events(id) on delete cascade,
  email_token          text,
  email_token_expiry   timestamptz,
  email_confirmed_at   timestamptz,
  admin_approved_at    timestamptz,
  admin_approved_by    bigint references public.users(id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index if not exists idx_registrations_email_token on public.registrations(email_token);
create index if not exists idx_registrations_status on public.registrations(status);
create index if not exists idx_registrations_event_id on public.registrations(event_id);
create index if not exists idx_registrations_email on public.registrations(email);

create table if not exists public.team_members (
  id         bigint generated by default as identity primary key,
  name       text not null,
  position   text not null,
  category   team_category not null,
  bio        text,
  image_url  text,
  email      text,
  phone      text,
  active     boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id           bigint generated by default as identity primary key,
  title        text not null,
  content      text not null,
  excerpt      text,
  category     event_category not null,
  status       post_status not null default 'DRAFT',
  image_url    text,
  featured     boolean not null default false,
  tags         text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  published_at timestamptz,
  author_id    bigint references public.users(id) on delete set null
);

create table if not exists public.contacts (
  id         bigint generated by default as identity primary key,
  name       text not null,
  email      text not null,
  phone      text,
  subject    text not null,
  message    text not null,
  status     contact_status not null default 'NEW',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.partners (
  id          bigint generated by default as identity primary key,
  name        text not null,
  description text,
  logo_url    text,
  website_url text,
  category    partner_category not null,
  active      boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.gallery_images (
  id          bigint generated by default as identity primary key,
  title       text,
  description text,
  filename    text,
  url         text not null,
  category    event_category,
  tags        text,
  size        integer,
  width       integer,
  height      integer,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Updated_at trigger helper
create or replace function public.set_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
do $$ begin
  create trigger trg_users_updated_at before update on public.users
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_events_updated_at before update on public.events
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_registrations_updated_at before update on public.registrations
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_team_members_updated_at before update on public.team_members
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_posts_updated_at before update on public.posts
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_contacts_updated_at before update on public.contacts
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_partners_updated_at before update on public.partners
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

do $$ begin
  create trigger trg_gallery_images_updated_at before update on public.gallery_images
  for each row execute function public.set_updated_at();
exception when duplicate_object then null; end $$;

-- Seed admin (same bcrypt hash as schema.sql: Admin123!)
insert into public.users (id, email, password_hash, name, role, active)
values (
  1,
  'admin@dorothy.local',
  '$2a$12$y7a6fGLOFgwDk3D6nHQmF.ONt5QdPRhF6l342XQI3/O0Mhq9H5W3y',
  'Admin Dorothy',
  'ADMIN',
  true
)
on conflict (id) do update set
  email = excluded.email,
  password_hash = excluded.password_hash,
  name = excluded.name,
  role = excluded.role,
  active = excluded.active;
